/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.cholewa.confluence.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloud.cholewa.confluence.JSON;

/**
 * ChangedValue
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ChangedValue {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_OLD_VALUE = "oldValue";
  @SerializedName(SERIALIZED_NAME_OLD_VALUE)
  private String oldValue;

  public static final String SERIALIZED_NAME_HIDDEN_OLD_VALUE = "hiddenOldValue";
  @SerializedName(SERIALIZED_NAME_HIDDEN_OLD_VALUE)
  private String hiddenOldValue;

  public static final String SERIALIZED_NAME_NEW_VALUE = "newValue";
  @SerializedName(SERIALIZED_NAME_NEW_VALUE)
  private String newValue;

  public static final String SERIALIZED_NAME_HIDDEN_NEW_VALUE = "hiddenNewValue";
  @SerializedName(SERIALIZED_NAME_HIDDEN_NEW_VALUE)
  private String hiddenNewValue;

  public ChangedValue() {
  }

  public ChangedValue name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public ChangedValue oldValue(String oldValue) {
    this.oldValue = oldValue;
    return this;
  }

   /**
   * Get oldValue
   * @return oldValue
  **/
  @javax.annotation.Nonnull
  public String getOldValue() {
    return oldValue;
  }

  public void setOldValue(String oldValue) {
    this.oldValue = oldValue;
  }


  public ChangedValue hiddenOldValue(String hiddenOldValue) {
    this.hiddenOldValue = hiddenOldValue;
    return this;
  }

   /**
   * Get hiddenOldValue
   * @return hiddenOldValue
  **/
  @javax.annotation.Nullable
  public String getHiddenOldValue() {
    return hiddenOldValue;
  }

  public void setHiddenOldValue(String hiddenOldValue) {
    this.hiddenOldValue = hiddenOldValue;
  }


  public ChangedValue newValue(String newValue) {
    this.newValue = newValue;
    return this;
  }

   /**
   * Get newValue
   * @return newValue
  **/
  @javax.annotation.Nonnull
  public String getNewValue() {
    return newValue;
  }

  public void setNewValue(String newValue) {
    this.newValue = newValue;
  }


  public ChangedValue hiddenNewValue(String hiddenNewValue) {
    this.hiddenNewValue = hiddenNewValue;
    return this;
  }

   /**
   * Get hiddenNewValue
   * @return hiddenNewValue
  **/
  @javax.annotation.Nullable
  public String getHiddenNewValue() {
    return hiddenNewValue;
  }

  public void setHiddenNewValue(String hiddenNewValue) {
    this.hiddenNewValue = hiddenNewValue;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangedValue changedValue = (ChangedValue) o;
    return Objects.equals(this.name, changedValue.name) &&
        Objects.equals(this.oldValue, changedValue.oldValue) &&
        Objects.equals(this.hiddenOldValue, changedValue.hiddenOldValue) &&
        Objects.equals(this.newValue, changedValue.newValue) &&
        Objects.equals(this.hiddenNewValue, changedValue.hiddenNewValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, oldValue, hiddenOldValue, newValue, hiddenNewValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangedValue {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    oldValue: ").append(toIndentedString(oldValue)).append("\n");
    sb.append("    hiddenOldValue: ").append(toIndentedString(hiddenOldValue)).append("\n");
    sb.append("    newValue: ").append(toIndentedString(newValue)).append("\n");
    sb.append("    hiddenNewValue: ").append(toIndentedString(hiddenNewValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("oldValue");
    openapiFields.add("hiddenOldValue");
    openapiFields.add("newValue");
    openapiFields.add("hiddenNewValue");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("oldValue");
    openapiRequiredFields.add("newValue");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ChangedValue
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChangedValue.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChangedValue is not found in the empty JSON string", ChangedValue.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChangedValue.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChangedValue` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ChangedValue.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("oldValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `oldValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("oldValue").toString()));
      }
      if ((jsonObj.get("hiddenOldValue") != null && !jsonObj.get("hiddenOldValue").isJsonNull()) && !jsonObj.get("hiddenOldValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hiddenOldValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hiddenOldValue").toString()));
      }
      if (!jsonObj.get("newValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `newValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("newValue").toString()));
      }
      if ((jsonObj.get("hiddenNewValue") != null && !jsonObj.get("hiddenNewValue").isJsonNull()) && !jsonObj.get("hiddenNewValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hiddenNewValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hiddenNewValue").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChangedValue.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChangedValue' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChangedValue> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChangedValue.class));

       return (TypeAdapter<T>) new TypeAdapter<ChangedValue>() {
           @Override
           public void write(JsonWriter out, ChangedValue value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChangedValue read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ChangedValue given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ChangedValue
  * @throws IOException if the JSON string is invalid with respect to ChangedValue
  */
  public static ChangedValue fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChangedValue.class);
  }

 /**
  * Convert an instance of ChangedValue to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

