/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.cholewa.confluence.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloud.cholewa.confluence.JSON;

/**
 * ContentMetadataCurrentuserFavourited
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ContentMetadataCurrentuserFavourited {
  public static final String SERIALIZED_NAME_IS_FAVOURITE = "isFavourite";
  @SerializedName(SERIALIZED_NAME_IS_FAVOURITE)
  private Boolean isFavourite;

  public static final String SERIALIZED_NAME_FAVOURITED_DATE = "favouritedDate";
  @SerializedName(SERIALIZED_NAME_FAVOURITED_DATE)
  private OffsetDateTime favouritedDate;

  public ContentMetadataCurrentuserFavourited() {
  }

  public ContentMetadataCurrentuserFavourited isFavourite(Boolean isFavourite) {
    this.isFavourite = isFavourite;
    return this;
  }

   /**
   * Get isFavourite
   * @return isFavourite
  **/
  @javax.annotation.Nullable
  public Boolean getIsFavourite() {
    return isFavourite;
  }

  public void setIsFavourite(Boolean isFavourite) {
    this.isFavourite = isFavourite;
  }


  public ContentMetadataCurrentuserFavourited favouritedDate(OffsetDateTime favouritedDate) {
    this.favouritedDate = favouritedDate;
    return this;
  }

   /**
   * Get favouritedDate
   * @return favouritedDate
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getFavouritedDate() {
    return favouritedDate;
  }

  public void setFavouritedDate(OffsetDateTime favouritedDate) {
    this.favouritedDate = favouritedDate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentMetadataCurrentuserFavourited contentMetadataCurrentuserFavourited = (ContentMetadataCurrentuserFavourited) o;
    return Objects.equals(this.isFavourite, contentMetadataCurrentuserFavourited.isFavourite) &&
        Objects.equals(this.favouritedDate, contentMetadataCurrentuserFavourited.favouritedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isFavourite, favouritedDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentMetadataCurrentuserFavourited {\n");
    sb.append("    isFavourite: ").append(toIndentedString(isFavourite)).append("\n");
    sb.append("    favouritedDate: ").append(toIndentedString(favouritedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("isFavourite");
    openapiFields.add("favouritedDate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ContentMetadataCurrentuserFavourited
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ContentMetadataCurrentuserFavourited.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ContentMetadataCurrentuserFavourited is not found in the empty JSON string", ContentMetadataCurrentuserFavourited.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ContentMetadataCurrentuserFavourited.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ContentMetadataCurrentuserFavourited` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ContentMetadataCurrentuserFavourited.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ContentMetadataCurrentuserFavourited' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ContentMetadataCurrentuserFavourited> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ContentMetadataCurrentuserFavourited.class));

       return (TypeAdapter<T>) new TypeAdapter<ContentMetadataCurrentuserFavourited>() {
           @Override
           public void write(JsonWriter out, ContentMetadataCurrentuserFavourited value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ContentMetadataCurrentuserFavourited read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ContentMetadataCurrentuserFavourited given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ContentMetadataCurrentuserFavourited
  * @throws IOException if the JSON string is invalid with respect to ContentMetadataCurrentuserFavourited
  */
  public static ContentMetadataCurrentuserFavourited fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ContentMetadataCurrentuserFavourited.class);
  }

 /**
  * Convert an instance of ContentMetadataCurrentuserFavourited to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

