/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.cholewa.confluence.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloud.cholewa.confluence.JSON;

/**
 * LongTaskStatusAdditionalDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LongTaskStatusAdditionalDetails {
  public static final String SERIALIZED_NAME_DESTINATION_ID = "destinationId";
  @SerializedName(SERIALIZED_NAME_DESTINATION_ID)
  private String destinationId;

  public static final String SERIALIZED_NAME_DESTINATION_URL = "destinationUrl";
  @SerializedName(SERIALIZED_NAME_DESTINATION_URL)
  private String destinationUrl;

  public static final String SERIALIZED_NAME_TOTAL_PAGE_NEED_TO_COPY = "totalPageNeedToCopy";
  @SerializedName(SERIALIZED_NAME_TOTAL_PAGE_NEED_TO_COPY)
  private Integer totalPageNeedToCopy;

  public static final String SERIALIZED_NAME_ADDITIONAL_PROPERTIES = "additionalProperties";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_PROPERTIES)
  private String additionalProperties;

  public LongTaskStatusAdditionalDetails() {
  }

  public LongTaskStatusAdditionalDetails destinationId(String destinationId) {
    this.destinationId = destinationId;
    return this;
  }

   /**
   * Get destinationId
   * @return destinationId
  **/
  @javax.annotation.Nullable
  public String getDestinationId() {
    return destinationId;
  }

  public void setDestinationId(String destinationId) {
    this.destinationId = destinationId;
  }


  public LongTaskStatusAdditionalDetails destinationUrl(String destinationUrl) {
    this.destinationUrl = destinationUrl;
    return this;
  }

   /**
   * Get destinationUrl
   * @return destinationUrl
  **/
  @javax.annotation.Nullable
  public String getDestinationUrl() {
    return destinationUrl;
  }

  public void setDestinationUrl(String destinationUrl) {
    this.destinationUrl = destinationUrl;
  }


  public LongTaskStatusAdditionalDetails totalPageNeedToCopy(Integer totalPageNeedToCopy) {
    this.totalPageNeedToCopy = totalPageNeedToCopy;
    return this;
  }

   /**
   * Get totalPageNeedToCopy
   * @return totalPageNeedToCopy
  **/
  @javax.annotation.Nullable
  public Integer getTotalPageNeedToCopy() {
    return totalPageNeedToCopy;
  }

  public void setTotalPageNeedToCopy(Integer totalPageNeedToCopy) {
    this.totalPageNeedToCopy = totalPageNeedToCopy;
  }


  public LongTaskStatusAdditionalDetails additionalProperties(String additionalProperties) {
    this.additionalProperties = additionalProperties;
    return this;
  }

   /**
   * Get additionalProperties
   * @return additionalProperties
  **/
  @javax.annotation.Nullable
  public String getAdditionalProperties() {
    return additionalProperties;
  }

  public void setAdditionalProperties(String additionalProperties) {
    this.additionalProperties = additionalProperties;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LongTaskStatusAdditionalDetails longTaskStatusAdditionalDetails = (LongTaskStatusAdditionalDetails) o;
    return Objects.equals(this.destinationId, longTaskStatusAdditionalDetails.destinationId) &&
        Objects.equals(this.destinationUrl, longTaskStatusAdditionalDetails.destinationUrl) &&
        Objects.equals(this.totalPageNeedToCopy, longTaskStatusAdditionalDetails.totalPageNeedToCopy) &&
        Objects.equals(this.additionalProperties, longTaskStatusAdditionalDetails.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destinationId, destinationUrl, totalPageNeedToCopy, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LongTaskStatusAdditionalDetails {\n");
    sb.append("    destinationId: ").append(toIndentedString(destinationId)).append("\n");
    sb.append("    destinationUrl: ").append(toIndentedString(destinationUrl)).append("\n");
    sb.append("    totalPageNeedToCopy: ").append(toIndentedString(totalPageNeedToCopy)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("destinationId");
    openapiFields.add("destinationUrl");
    openapiFields.add("totalPageNeedToCopy");
    openapiFields.add("additionalProperties");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to LongTaskStatusAdditionalDetails
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LongTaskStatusAdditionalDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LongTaskStatusAdditionalDetails is not found in the empty JSON string", LongTaskStatusAdditionalDetails.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!LongTaskStatusAdditionalDetails.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LongTaskStatusAdditionalDetails` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("destinationId") != null && !jsonObj.get("destinationId").isJsonNull()) && !jsonObj.get("destinationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destinationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinationId").toString()));
      }
      if ((jsonObj.get("destinationUrl") != null && !jsonObj.get("destinationUrl").isJsonNull()) && !jsonObj.get("destinationUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destinationUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinationUrl").toString()));
      }
      if ((jsonObj.get("additionalProperties") != null && !jsonObj.get("additionalProperties").isJsonNull()) && !jsonObj.get("additionalProperties").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `additionalProperties` to be a primitive type in the JSON string but got `%s`", jsonObj.get("additionalProperties").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LongTaskStatusAdditionalDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LongTaskStatusAdditionalDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LongTaskStatusAdditionalDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LongTaskStatusAdditionalDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<LongTaskStatusAdditionalDetails>() {
           @Override
           public void write(JsonWriter out, LongTaskStatusAdditionalDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LongTaskStatusAdditionalDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LongTaskStatusAdditionalDetails given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LongTaskStatusAdditionalDetails
  * @throws IOException if the JSON string is invalid with respect to LongTaskStatusAdditionalDetails
  */
  public static LongTaskStatusAdditionalDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LongTaskStatusAdditionalDetails.class);
  }

 /**
  * Convert an instance of LongTaskStatusAdditionalDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

