/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.cholewa.confluence.model;

import java.util.Objects;
import cloud.cholewa.confluence.model.GenericLinksValue;
import cloud.cholewa.confluence.model.SearchResult;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloud.cholewa.confluence.JSON;

/**
 * SearchPageResponseSearchResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SearchPageResponseSearchResult {
  public static final String SERIALIZED_NAME_RESULTS = "results";
  @SerializedName(SERIALIZED_NAME_RESULTS)
  private List<SearchResult> results = new ArrayList<>();

  public static final String SERIALIZED_NAME_START = "start";
  @SerializedName(SERIALIZED_NAME_START)
  private Integer start;

  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private Integer limit;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private Integer size;

  public static final String SERIALIZED_NAME_TOTAL_SIZE = "totalSize";
  @SerializedName(SERIALIZED_NAME_TOTAL_SIZE)
  private Integer totalSize;

  public static final String SERIALIZED_NAME_CQL_QUERY = "cqlQuery";
  @SerializedName(SERIALIZED_NAME_CQL_QUERY)
  private String cqlQuery;

  public static final String SERIALIZED_NAME_SEARCH_DURATION = "searchDuration";
  @SerializedName(SERIALIZED_NAME_SEARCH_DURATION)
  private Integer searchDuration;

  public static final String SERIALIZED_NAME_ARCHIVED_RESULT_COUNT = "archivedResultCount";
  @SerializedName(SERIALIZED_NAME_ARCHIVED_RESULT_COUNT)
  private Integer archivedResultCount;

  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private Map<String, GenericLinksValue> links = new HashMap<>();

  public SearchPageResponseSearchResult() {
  }

  public SearchPageResponseSearchResult results(List<SearchResult> results) {
    this.results = results;
    return this;
  }

  public SearchPageResponseSearchResult addResultsItem(SearchResult resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @javax.annotation.Nonnull
  public List<SearchResult> getResults() {
    return results;
  }

  public void setResults(List<SearchResult> results) {
    this.results = results;
  }


  public SearchPageResponseSearchResult start(Integer start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @javax.annotation.Nonnull
  public Integer getStart() {
    return start;
  }

  public void setStart(Integer start) {
    this.start = start;
  }


  public SearchPageResponseSearchResult limit(Integer limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @javax.annotation.Nonnull
  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }


  public SearchPageResponseSearchResult size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nonnull
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }


  public SearchPageResponseSearchResult totalSize(Integer totalSize) {
    this.totalSize = totalSize;
    return this;
  }

   /**
   * Get totalSize
   * @return totalSize
  **/
  @javax.annotation.Nonnull
  public Integer getTotalSize() {
    return totalSize;
  }

  public void setTotalSize(Integer totalSize) {
    this.totalSize = totalSize;
  }


  public SearchPageResponseSearchResult cqlQuery(String cqlQuery) {
    this.cqlQuery = cqlQuery;
    return this;
  }

   /**
   * Get cqlQuery
   * @return cqlQuery
  **/
  @javax.annotation.Nonnull
  public String getCqlQuery() {
    return cqlQuery;
  }

  public void setCqlQuery(String cqlQuery) {
    this.cqlQuery = cqlQuery;
  }


  public SearchPageResponseSearchResult searchDuration(Integer searchDuration) {
    this.searchDuration = searchDuration;
    return this;
  }

   /**
   * Get searchDuration
   * @return searchDuration
  **/
  @javax.annotation.Nonnull
  public Integer getSearchDuration() {
    return searchDuration;
  }

  public void setSearchDuration(Integer searchDuration) {
    this.searchDuration = searchDuration;
  }


  public SearchPageResponseSearchResult archivedResultCount(Integer archivedResultCount) {
    this.archivedResultCount = archivedResultCount;
    return this;
  }

   /**
   * Get archivedResultCount
   * @return archivedResultCount
  **/
  @javax.annotation.Nullable
  public Integer getArchivedResultCount() {
    return archivedResultCount;
  }

  public void setArchivedResultCount(Integer archivedResultCount) {
    this.archivedResultCount = archivedResultCount;
  }


  public SearchPageResponseSearchResult links(Map<String, GenericLinksValue> links) {
    this.links = links;
    return this;
  }

  public SearchPageResponseSearchResult putLinksItem(String key, GenericLinksValue linksItem) {
    if (this.links == null) {
      this.links = new HashMap<>();
    }
    this.links.put(key, linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nonnull
  public Map<String, GenericLinksValue> getLinks() {
    return links;
  }

  public void setLinks(Map<String, GenericLinksValue> links) {
    this.links = links;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchPageResponseSearchResult searchPageResponseSearchResult = (SearchPageResponseSearchResult) o;
    return Objects.equals(this.results, searchPageResponseSearchResult.results) &&
        Objects.equals(this.start, searchPageResponseSearchResult.start) &&
        Objects.equals(this.limit, searchPageResponseSearchResult.limit) &&
        Objects.equals(this.size, searchPageResponseSearchResult.size) &&
        Objects.equals(this.totalSize, searchPageResponseSearchResult.totalSize) &&
        Objects.equals(this.cqlQuery, searchPageResponseSearchResult.cqlQuery) &&
        Objects.equals(this.searchDuration, searchPageResponseSearchResult.searchDuration) &&
        Objects.equals(this.archivedResultCount, searchPageResponseSearchResult.archivedResultCount) &&
        Objects.equals(this.links, searchPageResponseSearchResult.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(results, start, limit, size, totalSize, cqlQuery, searchDuration, archivedResultCount, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchPageResponseSearchResult {\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    totalSize: ").append(toIndentedString(totalSize)).append("\n");
    sb.append("    cqlQuery: ").append(toIndentedString(cqlQuery)).append("\n");
    sb.append("    searchDuration: ").append(toIndentedString(searchDuration)).append("\n");
    sb.append("    archivedResultCount: ").append(toIndentedString(archivedResultCount)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("results");
    openapiFields.add("start");
    openapiFields.add("limit");
    openapiFields.add("size");
    openapiFields.add("totalSize");
    openapiFields.add("cqlQuery");
    openapiFields.add("searchDuration");
    openapiFields.add("archivedResultCount");
    openapiFields.add("_links");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("results");
    openapiRequiredFields.add("start");
    openapiRequiredFields.add("limit");
    openapiRequiredFields.add("size");
    openapiRequiredFields.add("totalSize");
    openapiRequiredFields.add("cqlQuery");
    openapiRequiredFields.add("searchDuration");
    openapiRequiredFields.add("_links");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SearchPageResponseSearchResult
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SearchPageResponseSearchResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SearchPageResponseSearchResult is not found in the empty JSON string", SearchPageResponseSearchResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SearchPageResponseSearchResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SearchPageResponseSearchResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SearchPageResponseSearchResult.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("results").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `results` to be an array in the JSON string but got `%s`", jsonObj.get("results").toString()));
      }

      JsonArray jsonArrayresults = jsonObj.getAsJsonArray("results");
      // validate the required field `results` (array)
      for (int i = 0; i < jsonArrayresults.size(); i++) {
        SearchResult.validateJsonElement(jsonArrayresults.get(i));
      };
      if (!jsonObj.get("cqlQuery").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cqlQuery` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cqlQuery").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SearchPageResponseSearchResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SearchPageResponseSearchResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SearchPageResponseSearchResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SearchPageResponseSearchResult.class));

       return (TypeAdapter<T>) new TypeAdapter<SearchPageResponseSearchResult>() {
           @Override
           public void write(JsonWriter out, SearchPageResponseSearchResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SearchPageResponseSearchResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SearchPageResponseSearchResult given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SearchPageResponseSearchResult
  * @throws IOException if the JSON string is invalid with respect to SearchPageResponseSearchResult
  */
  public static SearchPageResponseSearchResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchPageResponseSearchResult.class);
  }

 /**
  * Convert an instance of SearchPageResponseSearchResult to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

