/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.cholewa.confluence.model;

import java.util.Objects;
import cloud.cholewa.confluence.model.GenericLinksValue;
import cloud.cholewa.confluence.model.SpaceSettingsEditor;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloud.cholewa.confluence.JSON;

/**
 * SpaceSettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SpaceSettings {
  public static final String SERIALIZED_NAME_ROUTE_OVERRIDE_ENABLED = "routeOverrideEnabled";
  @SerializedName(SERIALIZED_NAME_ROUTE_OVERRIDE_ENABLED)
  private Boolean routeOverrideEnabled;

  public static final String SERIALIZED_NAME_EDITOR = "editor";
  @SerializedName(SERIALIZED_NAME_EDITOR)
  private SpaceSettingsEditor editor;

  public static final String SERIALIZED_NAME_SPACE_KEY = "spaceKey";
  @SerializedName(SERIALIZED_NAME_SPACE_KEY)
  private String spaceKey;

  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private Map<String, GenericLinksValue> links = new HashMap<>();

  public SpaceSettings() {
  }

  public SpaceSettings routeOverrideEnabled(Boolean routeOverrideEnabled) {
    this.routeOverrideEnabled = routeOverrideEnabled;
    return this;
  }

   /**
   * Defines whether an override for the space home should be used. This is used in conjunction with a space theme provided by an app. For example, if this property is set to true, a theme can display a page other than the space homepage when users visit the root URL for a space. This property allows apps to provide content-only theming without overriding the space home.
   * @return routeOverrideEnabled
  **/
  @javax.annotation.Nonnull
  public Boolean getRouteOverrideEnabled() {
    return routeOverrideEnabled;
  }

  public void setRouteOverrideEnabled(Boolean routeOverrideEnabled) {
    this.routeOverrideEnabled = routeOverrideEnabled;
  }


  public SpaceSettings editor(SpaceSettingsEditor editor) {
    this.editor = editor;
    return this;
  }

   /**
   * Get editor
   * @return editor
  **/
  @javax.annotation.Nullable
  public SpaceSettingsEditor getEditor() {
    return editor;
  }

  public void setEditor(SpaceSettingsEditor editor) {
    this.editor = editor;
  }


  public SpaceSettings spaceKey(String spaceKey) {
    this.spaceKey = spaceKey;
    return this;
  }

   /**
   * Get spaceKey
   * @return spaceKey
  **/
  @javax.annotation.Nullable
  public String getSpaceKey() {
    return spaceKey;
  }

  public void setSpaceKey(String spaceKey) {
    this.spaceKey = spaceKey;
  }


  public SpaceSettings links(Map<String, GenericLinksValue> links) {
    this.links = links;
    return this;
  }

  public SpaceSettings putLinksItem(String key, GenericLinksValue linksItem) {
    if (this.links == null) {
      this.links = new HashMap<>();
    }
    this.links.put(key, linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nonnull
  public Map<String, GenericLinksValue> getLinks() {
    return links;
  }

  public void setLinks(Map<String, GenericLinksValue> links) {
    this.links = links;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpaceSettings spaceSettings = (SpaceSettings) o;
    return Objects.equals(this.routeOverrideEnabled, spaceSettings.routeOverrideEnabled) &&
        Objects.equals(this.editor, spaceSettings.editor) &&
        Objects.equals(this.spaceKey, spaceSettings.spaceKey) &&
        Objects.equals(this.links, spaceSettings.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routeOverrideEnabled, editor, spaceKey, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpaceSettings {\n");
    sb.append("    routeOverrideEnabled: ").append(toIndentedString(routeOverrideEnabled)).append("\n");
    sb.append("    editor: ").append(toIndentedString(editor)).append("\n");
    sb.append("    spaceKey: ").append(toIndentedString(spaceKey)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("routeOverrideEnabled");
    openapiFields.add("editor");
    openapiFields.add("spaceKey");
    openapiFields.add("_links");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("routeOverrideEnabled");
    openapiRequiredFields.add("_links");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SpaceSettings
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SpaceSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SpaceSettings is not found in the empty JSON string", SpaceSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SpaceSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SpaceSettings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SpaceSettings.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `editor`
      if (jsonObj.get("editor") != null && !jsonObj.get("editor").isJsonNull()) {
        SpaceSettingsEditor.validateJsonElement(jsonObj.get("editor"));
      }
      if ((jsonObj.get("spaceKey") != null && !jsonObj.get("spaceKey").isJsonNull()) && !jsonObj.get("spaceKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `spaceKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("spaceKey").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SpaceSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SpaceSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SpaceSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SpaceSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<SpaceSettings>() {
           @Override
           public void write(JsonWriter out, SpaceSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SpaceSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SpaceSettings given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SpaceSettings
  * @throws IOException if the JSON string is invalid with respect to SpaceSettings
  */
  public static SpaceSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SpaceSettings.class);
  }

 /**
  * Convert an instance of SpaceSettings to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

